### ISSUE TITLE
Typo in example at GITHUB readme.md

### ISSUE THREAD

**Issue by rcfmc** [astronautlabs/scte104#1]
Hello,

Thanks for sharing this library. I am willing to give it a try (happy to share test results or anything that you want to know about my use case).

I just noticed that there is a typo in the readme.md. This is written:

opID: SCTE104.OP.SPLICE,

and it should be: 

opID: SCTE104.MOP.SPLICE,

Thanks!

**Comment by rezonant** [comment]
Great to hear you may find a use for it! Thanks for letting me know about the typo, I'll put a correction in today. And please feel free to file any issues for other problems or features you'd like to see! 

Edit: Oh, and of course PRs are welcome!

**Comment by rezonant** [comment]
Fixed in b983d6d610ed52c04b7cf0be1434a73b7fb011f6

Thanks!
