### ISSUE TITLE
Bug: Unit confusion (seconds vs microseconds) in microseconds field of Keep Alive request (Client#alive())

### ISSUE THREAD

**Issue by enricovittorini** [astronautlabs/scte104#3]
https://github.com/astronautlabs/scte104/blob/51a6dd3af856df75d2278f56858f6ede84327514/src/client.ts#L78

hi! can you please explain the above line of code?
  let microseconds = (elapsed - seconds) * 1000;
here is seems that you are doing the difference between something in milliseconds (elapsed) and something in seconds (seconds).
Am i missing something?

thanks!

---

**Bug**: Unit confusion in `microseconds` field of `Time` structure delivered by `Client#alive()` in keep alive requests as specified in SCTE 104 2019 section 9.2.1
**Impact**: Affects @/scte104@1.0.0 and earlier

**Comment by rezonant** [comment]
Fixed in @/scte104@1.0.1. Affects @/scte104@1.0.0 and all earlier versions.

**Comment by rezonant** [comment]
Good catch @enricovittorini ! You can find the fixed logic here:

https://github.com/astronautlabs/scte104/blob/24ac153b34ee8a2d0c73e90fee3fbc9b3a2ba3e1/src/client.ts#L78

I believe this addresses the issue, let me know if you see anything wrong with it.
